version: "3"

services:

  eventsservice:
    build: .
    environment:
      - EVENTS_MONGO_HOST=mongodb
      - EVENTS_MONGO_PORT=27017
      - EVENTS_MONGO_USERNAME=eventsservice
      - EVENTS_MONGO_PASSWORD=mongo_password
      - EVENTS_MONGO_DATABASE=events
      - EVENTS_MONGO_COLLECTION=events
      - HTTP_SERVER_LISTEN=:80
    ports:
      - "10080:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.4
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eventsservice
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=events
    # volumes:
    #   - ./db-data/mogno:/data/db